export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_RECEIVE = "FETCH_DATA_RECEIVE";
export const FETCH_DATA_END = "FETCH_DATA_END";
export const SET_ID_EDITED_MESSAGE = "SET_ID_EDITED_MESSAGE";
