export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_RECEIVE = "FETCH_DATA_RECEIVE";
export const FETCH_DATA_FAIL = "FETCH_DATA_FAIL";
export const FETCH_DATA_END = "FETCH_DATA_END";
export const ADD_POST_TO_STORE = "ADD_POST_TO_STORE";
